### ISSUE TITLE
need to stop fans when drives are sleeping

### ISSUE THREAD

**Issue by kapari258** [KostyaEsmukov/afancontrol#11]
Hi author
I use afancontrol to control fan speed of my nas. Everything works good except when my hdds are all sleeping, hddtemp can't read hdd temperature and afancontrol switch to panic mode.
Here is my service status information:

```
Aug 30 18:15:15 pve afancontrol[26211]: Traceback (most recent call last):
Aug 30 18:15:15 pve afancontrol[26211]:   File "/root/.local/pipx/venvs/afancontrol/lib/python3.11/site-packages/afancontrol/temps.py", line 67, in _get_temp_status
Aug 30 18:15:15 pve afancontrol[26211]:     sensor_value: Optional[TempStatus] = temp.get()
Aug 30 18:15:15 pve afancontrol[26211]:                                          ^^^^^^^^^^
Aug 30 18:15:15 pve afancontrol[26211]:   File "/root/.local/pipx/venvs/afancontrol/lib/python3.11/site-packages/afancontrol/temp/base.py", line 25, in get
Aug 30 18:15:15 pve afancontrol[26211]:     temp, min_t, max_t = self._get_temp()
Aug 30 18:15:15 pve afancontrol[26211]:                          ^^^^^^^^^^^^^^^^
Aug 30 18:15:15 pve afancontrol[26211]:   File "/root/.local/pipx/venvs/afancontrol/lib/python3.11/site-packages/afancontrol/temp/hdd.py", line 87, in _get_temp
Aug 30 18:15:15 pve afancontrol[26211]:     raise RuntimeError(
Aug 30 18:15:15 pve afancontrol[26211]: RuntimeError: hddtemp returned empty list of valid temperature
```
I read the code and i think the service will switch to panic mode as soon as it can't get temperature information from hddtemp, so it's no use to add another temperature to my hdd fan controlling map. Can you give me some advice about it? Thanks a lot!

**Comment by KostyaEsmukov** [comment]
I, personally, would probably have went with disabling the hdds' sleep mode. Not just because of the issue with reading their temperatures, but also because of the delay on accessing the data when the spindles are spinning up, and because it's considered more mechanically wearing than the constant 24/7 spinning.

But, if you choose to keep the sleep mode enabled, one option you have is to switch from temp `type = hdd` to `type = exec`, where you can handle the sleep mode in the `command` script.
